### ISSUE TITLE
BimayInstantVidcon (Linux)

### ISSUE THREAD

**Issue by idjoo** [ayangd/BimayInstantVicon#1]
Bro gw binusian 23 dr jurusan cyber security kebetulan gw ga punya windows dan main OS gw linux. Ada caranya ga ya bro biar bisa di run di linux. Apakah langsung di gcc saja main.cpp nya seperti kaya run golang?. 

P. S. Maaf saya Newbie

**Comment by RoARene317** [comment]
Kalau saya sih ada rekomendasi untuk bikin command buat compilenya di AUR. Soalnya AUR lebih enak.

**Comment by ayangd** [comment]
@cocatrip Coba pake Wine bro.

**Comment by idjoo** [comment]
> Kalau saya sih ada rekomendasi untuk bikin command buat compilenya di AUR. Soalnya AUR lebih enak.

Iya betul ini sebenernya mau dibikin aur nya lagi otw

> @cocatrip Coba pake Wine bro.

Wine sudah dicoba dan berhasil tapi jadi kurang efisien karena ga bisa langsung di akses kayanya memang harus bikin package AUR tapi gw gtw cara compilenya kalau di `gcc main.cpp` outputnya: 
```
main.cpp:9:10: fatal error: nlohmann/json.hpp: No such file or directory
    9 | #include <nlohmann/json.hpp>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```
mungkin seharusnya ga gw gcc, gw kurang tau juga, apa harus bikin makefile kah? mohon pencerahannya suhu... @ayangd  
Update:
dicoba lagi pake g++ `g++ main.cpp` hasilnya sama...

**Comment by ayangd** [comment]
Kodingnya masih belum bisa langsung compile ke native linux sih. Ntar gw coba port ke linux dulu, baru release.

**Comment by idjoo** [comment]
> Kodingnya masih belum bisa langsung compile ke native linux sih. Ntar gw coba port ke linux dulu, baru release.

Wah thanks banget brow, efisien banget ini brow kalo buat yang main OS nya linux, soalnya nantinya bisa dijadiin cli app
