### ISSUE TITLE
Identify XB class as Lab 

### ISSUE THREAD

**Issue by RoARene317** [ayangd/BimayInstantVicon#3]
![image](https://user-images.githubusercontent.com/24410807/95821113-8b924e00-0d53-11eb-9407-a24221cad5a0.png)
XB class which is combined lab class is not detected as lab class, please auto redirect to zoom meetings and also competition.binus.ac.id or laboratory.binus.ac.id. Thank you

**Comment by ayangd** [comment]
I was also encountered that problem. I'm gonna fix it soon.

**Comment by ayangd** [comment]
Fixed at [this commit](https://github.com/ayangd/BimayInstantVicon/commit/2b422718efd28146c15d503520608ebb121b04d2).
